# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghcp < Formula
  desc "Tool to fork a repository, commit files, create a pull request and upload assets using GitHub API
"
  homepage "https://github.com/suzuki-shunsuke/ghcp"
  version "1.14.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/ghcp/releases/download/v1.14.0/ghcp_darwin_arm64.tar.gz"
      sha256 "5e59c2ee33a325d90e74e32870725d33e8b7df1999c30322901372c344f1ca13"

      def install
        bin.install "ghcp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/ghcp/releases/download/v1.14.0/ghcp_darwin_amd64.tar.gz"
      sha256 "f97d91f4ddceff2c56606b666623d744ad9af6eb0565fdec6e02df37416c0743"

      def install
        bin.install "ghcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/ghcp/releases/download/v1.14.0/ghcp_linux_amd64.tar.gz"
      sha256 "1286d634214d6d16e7c9493503a8e5cddf42f400d8a03ae88963e40df014a85a"

      def install
        bin.install "ghcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/ghcp/releases/download/v1.14.0/ghcp_linux_arm64.tar.gz"
      sha256 "32dfd9f88715d95a8d3e570415d193f51203e6529f815295ac8fea451ed12344"

      def install
        bin.install "ghcp"
      end
    end
  end

  test do
    system "#{bin}/ghcp --version"
  end
end
