# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ghcp < Formula
  desc "Tool to fork a repository, commit files, create a pull request and upload assets using GitHub API
"
  homepage "https://github.com/suzuki-shunsuke/ghcp"
  version "1.15.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/ghcp/releases/download/v1.15.0/ghcp_darwin_amd64.tar.gz"
      sha256 "524745158ffa66b6540d5729bf6ae3225224c328f458b9148761e0c17b0ba983"

      def install
        bin.install "ghcp"
      end
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/ghcp/releases/download/v1.15.0/ghcp_darwin_arm64.tar.gz"
      sha256 "8b251d324489b0cda049f56db0bd389b763130d1dadf959ece60e23c59a076b7"

      def install
        bin.install "ghcp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghcp/releases/download/v1.15.0/ghcp_linux_amd64.tar.gz"
        sha256 "399bbe5e70c427bc44150010c50429ddfea393c1d4c0c24e13b68d12d4f46872"

        def install
          bin.install "ghcp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/suzuki-shunsuke/ghcp/releases/download/v1.15.0/ghcp_linux_arm64.tar.gz"
        sha256 "4b37c2652136c60c1b9b1f9cc6ae21f8b05e51061e9860eb30ac4aac3fa6be4b"

        def install
          bin.install "ghcp"
        end
      end
    end
  end

  test do
    system "#{bin}/ghcp --version"
  end
end
